In [1]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
import torch

c:\Users\ATHUL AKSHAY\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [3]:
data=pd.read_csv(r'C:\Users\ATHUL AKSHAY\Desktop\Machine Learning Projects\Pytorch projects\iris.xls')
data.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
data.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [5]:
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
data['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['species']=le.fit_transform(data['species'])
data['species'].unique()

array([0, 1, 2])

In [8]:
data.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [9]:
x=data.iloc[:,[0,1,2,3]]
y=data.iloc[:,4]

In [10]:
print('X-axis',x)
print('Y-axis',y)

X-axis      sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
Y-axis 0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32


In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
x_train

sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]

In [14]:
print(len(x_train))
print(len(x_test))

120
30


In [15]:
print(len(y_train))
print(len(y_test))

120
30


In [16]:
sc=StandardScaler()
sc

StandardScaler()

In [17]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
x_train

array([[-1.47393679,  1.22037928, -1.5639872 , -1.30948358],
       [-0.13307079,  3.02001693, -1.27728011, -1.04292204],
       [ 1.08589829,  0.09560575,  0.38562104,  0.28988568],
       [-1.23014297,  0.77046987, -1.21993869, -1.30948358],
       [-1.7177306 ,  0.32056046, -1.39196294, -1.30948358],
       [ 0.59831066, -1.25412249,  0.72966956,  0.95628954],
       [ 0.72020757,  0.32056046,  0.44296246,  0.42316645],
       [-0.74255534,  0.99542457, -1.27728011, -1.30948358],
       [-0.98634915,  1.22037928, -1.33462153, -1.30948358],
       [-0.74255534,  2.34515281, -1.27728011, -1.44276436],
       [-0.01117388, -0.80421307,  0.78701097,  0.95628954],
       [ 0.23261993,  0.77046987,  0.44296246,  0.55644722],
       [ 1.08589829,  0.09560575,  0.5576453 ,  0.42316645],
       [-0.49876152,  1.8952434 , -1.39196294, -1.04292204],
       [-0.49876152,  1.44533399, -1.27728011, -1.30948358],
       [-0.37686461, -1.47907719, -0.01576889, -0.24323741],
       [ 0.59831066, -0.

In [19]:
type(y_train)

pandas.core.series.Series

In [20]:
type(y_test)

pandas.core.series.Series

In [21]:
x_train=torch.FloatTensor(x_train)
x_test=torch.FloatTensor(x_test)
y_train=torch.LongTensor(y_train)
y_test=torch.LongTensor(y_test.values.astype(int))

In [22]:
print('X Train :',x_train[:5])
print('Y Train :',y_train[:10])

X Train : tensor([[-1.4739,  1.2204, -1.5640, -1.3095],
        [-0.1331,  3.0200, -1.2773, -1.0429],
        [ 1.0859,  0.0956,  0.3856,  0.2899],
        [-1.2301,  0.7705, -1.2199, -1.3095],
        [-1.7177,  0.3206, -1.3920, -1.3095]])
Y Train : tensor([0, 0, 1, 0, 0, 2, 1, 0, 0, 0])


In [23]:
print('X Test :',x_test[:5])
print('Y Test :',y_test[:10])

X Test : tensor([[ 0.1444, -0.6345,  0.4511, -0.0794],
        [-0.3370,  2.0093, -1.2060, -1.2083],
        [ 2.0702, -1.1633,  1.6663,  1.3003],
        [ 0.0241, -0.3701,  0.3406,  0.2968],
        [ 0.9870, -0.6345,  0.5063,  0.1714]])
Y Test : tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1])


In [24]:
import torch.nn as nn

In [25]:
class neuralnetwork(nn.Module):
    def __init__(self,input_dim,output_dim):
        super(neuralnetwork,self).__init__()
        self.input_layer=nn.Linear(input_dim,128)
        self.hidden_layer1=nn.Linear(128,64)
        self.output_layer=nn.Linear(64,output_dim)
        self.relu=nn.ReLU()

    def forward(self,x):
        x=self.input_layer(x)
        x=self.relu(x)
        x=self.hidden_layer1(x)
        x=self.relu(x)
        x=self.output_layer(x)
        return x
input_dim=4      # 4 Columns
output_dim=3     # 3 Flowers
model=neuralnetwork(input_dim,output_dim)

In [26]:
model

neuralnetwork(
  (input_layer): Linear(in_features=4, out_features=128, bias=True)
  (hidden_layer1): Linear(in_features=128, out_features=64, bias=True)
  (output_layer): Linear(in_features=64, out_features=3, bias=True)
  (relu): ReLU()
)

In [27]:
learningrate=0.01
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=learningrate)

In [28]:
criterion

CrossEntropyLoss()

In [29]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

In [30]:
def train(model,optimizer,criterion,x_train,y_train,x_test,y_test,num_epochs,train_losses,test_losses):
    for epoch in range(num_epochs):
        optimizer.zero_grad()
        output_train=model(x_train)
        # print(output_train)
        loss_train=criterion(output_train,y_train) # Calculate the loss
        # print(loss_train)
        loss_train.backward()
        optimizer.step() # Calculate Weights
        output_test=model(x_test)
        loss_test=criterion(output_test,y_test)
        train_losses[epoch]=loss_train.item()
        test_losses[epoch]=loss_test.item()
        if (epoch+1)%50==0:
            print(f'Epoch{epoch+1}/{num_epochs},Train Loss:{loss_train.item():4f},Test Loss:{loss_test.item():4f}')

In [31]:
num_epochs=1000
train_losses=np.zeros(num_epochs)
test_losses=np.zeros(num_epochs)

In [32]:
print(len(train_losses))
print(len(test_losses))

1000
1000


In [33]:
train_losses[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
test_losses[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
train(model,optimizer,criterion,x_train,y_train,x_test,y_test,num_epochs,train_losses,test_losses)

Epoch50/1000,Train Loss:0.023658,Test Loss:0.146161
Epoch100/1000,Train Loss:0.001098,Test Loss:0.612577
Epoch150/1000,Train Loss:0.000252,Test Loss:0.698683
Epoch200/1000,Train Loss:0.000129,Test Loss:0.736846
Epoch250/1000,Train Loss:0.000080,Test Loss:0.758010
Epoch300/1000,Train Loss:0.000055,Test Loss:0.772813
Epoch350/1000,Train Loss:0.000041,Test Loss:0.786640
Epoch400/1000,Train Loss:0.000031,Test Loss:0.797767
Epoch450/1000,Train Loss:0.000025,Test Loss:0.806929
Epoch500/1000,Train Loss:0.000020,Test Loss:0.814985
Epoch550/1000,Train Loss:0.000017,Test Loss:0.820990
Epoch600/1000,Train Loss:0.000014,Test Loss:0.826573
Epoch650/1000,Train Loss:0.000012,Test Loss:0.831811
Epoch700/1000,Train Loss:0.000011,Test Loss:0.836773
Epoch750/1000,Train Loss:0.000009,Test Loss:0.841388
Epoch800/1000,Train Loss:0.000008,Test Loss:0.845550
Epoch850/1000,Train Loss:0.000007,Test Loss:0.849747
Epoch900/1000,Train Loss:0.000007,Test Loss:0.853579
Epoch950/1000,Train Loss:0.000006,Test Loss:0.8

In [36]:
predictiontrain=[]
predictiontest=[]
with torch.no_grad():
    predictiontrain=model(x_train)
    predictiontest=model(x_test)

In [37]:
predictiontrain[:10]

tensor([[ 32.0905,   6.6039, -44.6831],
        [ 30.8014,  12.1171, -50.8166],
        [ -7.1730,  16.0063, -10.9338],
        [ 26.0912,   6.2110, -37.3086],
        [ 28.1659,   1.6643, -34.5314],
        [-18.8175,   1.4035,  14.2123],
        [ -6.4736,  13.7551,  -9.0958],
        [ 24.7600,   8.2887, -38.4317],
        [ 27.4951,   8.3697, -41.6587],
        [ 31.8019,   9.8216, -48.7559]])

In [38]:
len(predictiontest)

30

In [39]:
x_test.size()

torch.Size([30, 4])

In [40]:
x_test.size(1)

4

In [41]:
predictiontest[:10]

tensor([[ -7.2370,  15.1774,  -9.6675],
        [ 26.5574,   9.6394, -42.5266],
        [-29.6036, -29.2560,  53.3178],
        [ -7.2297,  14.1736,  -8.5796],
        [-10.3405,  10.6166,  -2.2185],
        [ 23.3912,   8.6185, -37.3205],
        [ -2.3380,  13.9001, -13.7635],
        [-14.5400,   0.5346,  11.4149],
        [-18.7079,  10.3190,   5.8367],
        [ -6.3682,  16.6731, -12.1469]])

In [42]:
type(predictiontest)

torch.Tensor

In [43]:
def getaccuracy(pred_arr,original_arr):
    if len(pred_arr)!=len(original_arr):
        return False
    pred_arr=pred_arr.numpy()
    final_pred=[]
    # print(len(pred_arr))
    for i in range(len(pred_arr)):
        final_pred.append(np.argmax(pred_arr[i]))
    final_pred=np.array(final_pred)
    count=0
    
    for i in range(len(original_arr)):
        if final_pred[i]==original_arr[i]:
            count+=1
    return count/len(final_pred)


In [44]:
trainacc=getaccuracy(predictiontrain,y_train)
testacc=getaccuracy(predictiontest,y_test)

In [45]:
print('Training Accuracy',trainacc*100)
print('Testing Accuracy',testacc*100)

Training Accuracy 100.0
Testing Accuracy 90.0
